models:
  - name: SVAE-768-H1
    hidden_size: 768
    hidden_layers: 1
  - name: SVAE-768-H2
    hidden_size: 768
    hidden_layers: 2
  - name: SVAE-768-H4
    hidden_size: 768
    hidden_layers: 4
  - name: SVAE-1024-H1
    hidden_size: 1024
    hidden_layers: 1
  - name: SVAE-1024-H2
    hidden_size: 1024
    hidden_layers: 2
  - name: SVAE-1024-H4
    hidden_size: 1024
    hidden_layers: 4
  - name: SVAE-2048-H1
    hidden_size: 2048
    hidden_layers: 1
  - name: SVAE-2048-H2
    hidden_size: 2048
    hidden_layers: 2
  - name: SVAE-2048-H4
    hidden_size: 2048
    hidden_layers: 4
